<a href="https://colab.research.google.com/github/kdwivedi1985git/datascience/blob/main/numpy/numpy_universalfunctions_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy functions - operate on the ndarray object.

Universal Functions are used for vectorization

Converting iterative statements into a vector based operation is called vectorization.

built-in "zip" function- create a vector from x and y array.


In [ ]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [ ]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

z=np.add(x,y)
print(z)

print(np.all(x))

print(np.amax(z))

#np.amin
print(np.angle(x))
print(np.any(y))
print(np.append(x,y))


[ 5  7  9 11]
True
11
[0. 0. 0. 0.]
True
[1 2 3 4 4 5 6 7]


## Create Your Own ufunc (Universal Function)

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.

In [ ]:
import numpy as np

arr1=[1,2,3,4,5]

stringgenerator=np.frompyfunc(str,1,1)
print("List of Strings from numbers::", stringgenerator(arr1))

def maxbetween2list(x,y):
   max=0
   for i, j in zip(list(str(x)),list(str(y))):
       max=0
       i1,j1=int(i),int(j)
       if int(i1) > max:
           max=i1
       if int(j1) > max:
           max=j1

       return max


def arrReverse(x):
    s=str(x)
    return s[::-1]

# user-defined function to check
# whether a no. is palindrome or not
def fun(x):
    s = str(x)
    return s[::-1]== s





a = np.array([345, 122, 454, 232, 334, 56, 66])
# 'check_palindrome' as universal function
check_palindrome = np.frompyfunc(fun, 1, 1)
print("Original array-", a)
print("Checking of number as palindrome-",
                      check_palindrome(a))


rev=np.frompyfunc(arrReverse,1,1)
print(rev(a))


x=[1,2,3,4,5]
y=np.array(x)

print("x=",x)
print("y=",y)
z=list(y)
print("z=",z)


p=np.array([1,2,3,4,5,5,7,8])
q=np.array([4,3,5,2,1,8,9,7])

maxres=np.frompyfunc(maxbetween2list,2,1)
print(">>",maxres(p,q))

List of Strings from numbers:: ['1' '2' '3' '4' '5']
Original array- [345 122 454 232 334  56  66]
Checking of number as palindrome- [False False True True False False True]
['543' '221' '454' '232' '433' '65' '66']
x= [1, 2, 3, 4, 5]
y= [1 2 3 4 5]
z= [1, 2, 3, 4, 5]
>> [4 3 5 4 5 8 9 8]


#### Simple Arithmetic
add, subtract, multipy, divide, mod, remainder, power, divmod, absolute

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3 = np.array([-20, 21, -22, 23.3, 24, 25])

print("divide=",np.divide(arr1,arr2))
print("div and mode=",np.divmod(arr1,arr2))
print("remainder=",np.remainder(arr1,arr2))
print("power=",np.power(arr1,arr2))
print("absolute=",np.absolute(arr3))

divide= [0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]
div and mode= (array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))
remainder= [10 20  8 17  2 10]
power= [1661992960          0 1749024768          0 1090519040          0]
absolute= [20.  21.  22.  23.3 24.  25. ]


#### Rounding Decimals
truncation- remove decimal
fix - removes decimal
rounding-
floor
ceil

In [ ]:
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


#### NumPy Logs

log2

log10

#### summation

add

sum

sum with axis


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print("Vertical sum=",np.sum([arr1, arr2], axis=0))
print("Horizontal sum=",np.sum([arr1, arr2], axis=1))

Vertical sum= [2 4 6]
Horizontal sum= [6 6]


#### Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10]

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


#### Product

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

np.prod(arr1)
np.prod([arr1, arr2])

np.prod([arr1, arr2], axis=1)

np.prod([arr1, arr2], axis=1)

array([  24, 1680])

#### Difference

In [ ]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr1 = np.diff(arr)
newarr2 = np.diff(arr, n=2)

print(newarr1)
print(newarr2)

[  5  10 -20]
[  5 -30]


#### Set Operations

In [ ]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)



arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)




arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

newarr = np.setdiff1d(arr1, arr2, assume_unique=True)

print(newarr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]


#### LCM Lowest Common Multiple
#### GCD Greatest Common Denominator
#### Trigonometric Functions- sin, cos tan
#### Hyperbolic Functions- sinh, cosh, tanh

#exponential

np.exp()  - thins equals to np.power(2.71,n)

In [ ]:
np.exp(2)

#by default e=2.71

7.38905609893065

In [ ]:
arr=np.array([1,2,3,4])
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
#inverse of array
matrix=np.arange(0,12).reshape(4,3)
print("matrix::",matrix)


print("\n inverse::",1/matrix)

#python adds "inf" for divide by zero error

matrix:: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 inverse:: [[       inf 1.         0.5       ]
 [0.33333333 0.25       0.2       ]
 [0.16666667 0.14285714 0.125     ]
 [0.11111111 0.1        0.09090909]]


C:\Users\dwivedik\AppData\Local\Temp\ipykernel_4348\544368070.py:6: RuntimeWarning: divide by zero encountered in divide
  print("\n inverse::",1/matrix)


In [ ]:
m1=np.arange(1,10).reshape(3,3)
m2=np.arange(11,20).reshape(3,3)

print("###########Matrix multiplication or dot product using @ sign###################")
m3=m1 @ m2
print(m3)

print("\n###########Transpose###################")
print(np.transpose(m3))


###########Matrix multiplication or dot product using @ sign###################
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

###########Transpose###################
[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]


In [ ]:
print("\n###########Other way to transpose ###################")
m3.T



###########Other way to transpose ###################


array([[ 90, 216, 342],
       [ 96, 231, 366],
       [102, 246, 390]])

In [ ]:
v1=np.linspace(20,50,3)
v2=np.linspace(100,120,3)
print(v1+v2)

print("you can't add two arrays if dimentions are not same, it will throw error")
v1=np.linspace(20,50,4) #dim 4
v2=np.linspace(100,120,3) #dim 3
#print(v1+v2)  #it will throw error

[120. 145. 170.]
you can't add two arrays if dimentions are not same


In [ ]:
v1=np.arange(2,5,1)
print(v1)
print(1/v1)
print(v1**2)

[2 3 4]
[0.5        0.33333333 0.25      ]
[ 4  9 16]
