<a href="https://colab.research.google.com/github/kdwivedi1985git/datascience/blob/main/numpy/numpy_basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

### Numpy Array and Indexing

In [ ]:
import numpy as np

print("numpy path::",np.version)
print("numpy version::",np.__version__)

arr1D=np.array([1,2,3,4,5,6])
arr2D=np.array([[1,2,3,],[4,5,6]])
arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,8,8]]])

print("1 D Array::",arr1D)
print("\n2 D Array::",arr2D)
print("\n3 D Array::",arr3D)

numpy path:: <module 'numpy.version' from 'c:\\Users\\dwivedik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\version.py'>
numpy version:: 1.25.2
1 D Array:: [1 2 3 4 5 6]

2 D Array:: [[1 2 3]
 [4 5 6]]

3 D Array:: [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 8 8]]]


### Reading values for array indexes

In [ ]:
import numpy as np

arr1D=np.array([1,2,3,4,5,6])
arr2D=np.array([[1,2,3,],[4,5,6]])
arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,8,8]]])

print('4th element on 1st row from arr1D::',arr1D[3])
print('\n2ed element on 2nd row::',arr2D[1,1])
print('\nLast element from 2nd dim arr2D::',arr2D[1,-1])
print('\nThird element of the second array of the first from 3D::',arr3D[1,0,2])


4th element on 1st row from arr1D:: 4

2ed element on 2nd row:: 5

Last element from 2nd dim arr2D:: 6

Third element of the second array of the first from 3D:: 9


### Slicing

In [ ]:
import numpy as np

arr1D=np.array([1,2,3,4,5,6])
arr2D=np.array([[1,2,3,4,5,6],[7,8,9,1,2,3]])
arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,8,8]]])

print("##########1D Array##########\n")
print("All in arr1D::",arr1D[:])
print("All after 1st in arr1D::",arr1D[1:])
print("All before 4th in arr1D::",arr1D[:3])
print("All after 3rd index in arr1D::",arr1D[2::])
print("Every other element from array in arr1D::",arr1D[::2])
print("Every other element between 1 to 3::",arr1D[1:4:2])
print("Every third element between 1 to 5::",arr1D[1:4:3])
print("All in reverse order from arr1D::",arr1D[::-1])
print("3rd from last to end arr1D::",arr1D[-4:-1])

print("\n##########2D Array##########\n")
print("In 2DArr from second element, slice elements from index 1 to index 4::",arr2D[1,1:5])
print("In 2DArr From both elements, return index 2::",arr2D[:,2])
print("In 2DArr From both elements, return index 2::",arr2D[0:2,2])
print("In 2DArr From both elements, slice index 1 to index 4. This is give 2D array::",arr2D[0:2,1:4])


print("\n##########3D Array##########\n")
print("In 3DArr from all elements, slice elements from index 1 to index 2::",arr3D[:,:,1:2])

##########1D Array##########

All in arr1D:: [1 2 3 4 5 6]
All after 1st in arr1D:: [2 3 4 5 6]
All before 4th in arr1D:: [1 2 3]
All after 3rd index in arr1D:: [3 4 5 6]
Every other element from array in arr1D:: [1 3 5]
Every other element between 1 to 3:: [2 4]
Every third element between 1 to 5:: [2]
All in reverse order from arr1D:: [6 5 4 3 2 1]
3rd from last to end arr1D:: [3 4 5]

##########2D Array##########

In 2DArr from second element, slice elements from index 1 to index 4:: [8 9 1 2]
In 2DArr From both elements, return index 2:: [3 9]
In 2DArr From both elements, return index 2:: [3 9]
In 2DArr From both elements, slice index 1 to index 4. This is give 2D array:: [[2 3 4]
 [8 9 1]]

##########3D Array##########

In 3DArr from all elements, slice elements from index 1 to index 2:: [[[2]
  [5]]

 [[8]
  [8]]]


### Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

### Checking datatype of array

In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print("arr type-",arr.dtype)

arr1 = np.array([1,2,3,4,5])
print("arr type-",arr1.dtype)


arr type- <U6
arr type- int32


### Changing the datatype of array using "dtype"

In [ ]:
import numpy as np

arr = np.array(['1','2','3','4','5'])

print("current datatype-",arr.dtype)

arr1 = np.array(['1','2','3','4','5'],dtype='i')
print("current datatype-",arr1.dtype)

arr3 = np.array([1, 2, 3, 4], dtype='S')
print("current datatype-",arr3.dtype)



current datatype- <U1
current datatype- int32
current datatype- |S1


### NumPy Array Copy vs View

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr1= arr.copy()

arr2= arr.view()

arr1[0]=0
arr2[1]=10

print("Original Array::",arr)
print("copied array after chnages::",arr1)
print("view array after the changes original::",arr2)
print("Original Array after view array was chnaged::",arr)

Original Array:: [ 1 10  3  4  5]
copied array after chnages:: [0 2 3 4 5]
view array after the changes original:: [ 1 10  3  4  5]
Original Array:: [ 1 10  3  4  5]


#### NumPy Array Shape-

shape

ndmin - to change the dimension of array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Array-",arr, "---shape::",arr.shape)


arr1 = np.array([1, 2, 3, 4], ndmin=5)
print("\nArray arr1 -",arr1, "---shape::",arr1.shape)

arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], ndmin=5)
print("\nArray arr2-",arr2, "---shape::",arr2.shape)

Array- [[1 2 3 4]
 [5 6 7 8]] ---shape:: (2, 4)

Array arr1 - [[[[[1 2 3 4]]]]] ---shape:: (1, 1, 1, 1, 4)

Array arr2- [[[[[1 2 3 4]
    [5 6 7 8]]]]] ---shape:: (1, 1, 1, 2, 4)


#### Array Reshaping- reshape

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr1 = arr.reshape(4, 3)
print("\nnewarr1::",newarr1)

newarr2=arr.reshape(2,3,2)
print('\nnewarr2::',newarr2)

newarr3=arr.reshape(2,2,3)
print('\nnewarr3::',newarr3)

newarr4=arr.reshape(3,2,-1) #-1 will automatically calculate the number for us
print('\nnewarr4::',newarr4)

newarr5=arr.reshape(3,-1,2) #-1 will automatically calculate the number for us
print('\nnewarr5::',newarr5)

print('\nnewarr3 change to original::',newarr3.base)

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[ 9,10],[11,12]]])
print('\n arr3D change to 1D::',arr3D.reshape(-1))







newarr1:: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

newarr2:: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

newarr3:: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

newarr5:: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

newarr3 change to original:: [ 1  2  3  4  5  6  7  8  9 10 11 12]

 arr3D change to 1D:: [ 1  2  3  4  5  6  7  8  9 10 11 12]


#### Array Iterations

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for ele in arr:
  print("\nele::",ele)

print("\n###############")
for ele in arr:
  for i in ele:
    print("i=",i)


print("\n###############")
for ele in arr:
  for i in ele:
    for j in i:
      print("j=",j)



ele:: [[1 2 3]
 [4 5 6]]

ele:: [[ 7  8  9]
 [10 11 12]]

###############
i= [1 2 3]
i= [4 5 6]
i= [7 8 9]
i= [10 11 12]

###############
j= 1
j= 2
j= 3
j= 4
j= 5
j= 6
j= 7
j= 8
j= 9
j= 10
j= 11
j= 12


#### Array iteration with "nditer" - to read each element as 1D

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for ele in np.nditer(arr):
    print(ele)


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("\n###############")
for x in np.nditer(arr[:, ::2]):
  print(x)


print("\n###############")
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

print("\n###############")
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
9
10
11
12

###############
1
3
5
7

###############
(0,) 1
(1,) 2
(2,) 3

###############
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#### Join, Split-
concatenate

stack- If axis is not explicitly passed it is taken as 0.

hstack

vstack

dstack

In [ ]:
import numpy as np

arr11 = np.array([1, 2, 3])

arr22 = np.array([4, 5, 6])

arr3=np.concatenate((arr11,arr22),axis=0)

print("\nconcatenate with axis=0 joins horizontally::",arr3)


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3=np.concatenate((arr1,arr2),axis=1)

print("\nconcatenate with axis=1 joins vertically::",arr3)

arr4=np.stack((arr1,arr2),axis=1)
print("\n stack with axis=1->",arr4)

print("################Join without axis################")

arr5=np.vstack((arr11,arr22))
arr6=np.hstack((arr11,arr22))
arr7=np.dstack((arr11,arr22))

print("\n vstack arr5::",arr5)
print("\n hstack arr5::",arr6)
print("\n dstack arr5-to stack along height, which is the same as depth::",arr7)


concatenate with axis=0 joins horizontally:: [1 2 3 4 5 6]

concatenate with axis=1 joins vertically:: [[1 2 5 6]
 [3 4 7 8]]

 stack with axis=1-> [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
################Join without axis################

 vstack arr5:: [[1 2 3]
 [4 5 6]]

 hstack arr5:: [1 2 3 4 5 6]

 dstack arr5-to stack along height, which is the same as depth:: [[[1 4]
  [2 5]
  [3 6]]]


#### Split

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr1=np.array_split(arr,3)
print(arr1)

arr2 = np.array_split(arr, 4)
print(arr2)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr3=np.array_split(arr,5)
print(arr3)

arr4 = np.vsplit(arr, 3)
print(arr4)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


#### Search, sort and filter

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
###Tells the index
x=np.where(arr==4)
print(x)

y=np.where(arr%2==0)
print(y)

z=np.searchsorted(arr,5)
print(z)

a=np.searchsorted(arr,4,side='left')
print(a)

b=np.searchsorted(arr,4,side='right')
print(b)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
7
3
7


In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
import numpy as np

demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [ ]:
demo_matrix=np.array([1,2,3,4,5,6,7,8,9,10])
demo_matrix[0:7]=5
demo_matrix

array([ 5,  5,  5,  5,  5,  5,  5,  8,  9, 10])

In [ ]:
import numpy as np
demo_array = np.arange(0,10)  #Arrange data from start to end.
print(demo_array)
demo_array<3


[0 1 2 3 4 5 6 7 8 9]


array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
import numpy as np

#help(np.arange)
arr1=arr=np.arange(start=0,stop=30,step=5)
print(arr1)

[ 0  5 10 15 20 25]


#### np.linspace()-> returns numbers which are evenly distributes
start: default=0

stop: end of interval

num: no of samples to generate, default =50

In [ ]:
print(np.linspace(0,5))
print(np.linspace(0,50,100))

#end-start/49
#(5-0)/49 for 50 samples

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
[ 0.          0.50505051  1.01010101  1.51515152  2.02020202  2.52525253
  3.03030303  3.53535354  4.04040404  4.54545455  5.05050505  5.55555556
  6.06060606  6.56565657  7.07070707  7.57575758  8.08080808  8.58585859
  9.09090909  9.5959596  10.1010101  10.60606061 11.11111111 11.61616162
 12.12121212 12.62626263 13.13131313 13.63636364 14.14141414 14.64646465
 15.15151515 15.65656566 16.16161616 16.66666667 17.17171717 17.67676768
 1

In [ ]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

np.zeros()-> returns a matrix filled with zeros

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

np.eye()-> Creates identitiy matrix->matrix with diagonal one and zeros at other places

In [ ]:
print(np.eye(5,5))

print("\n ##################")

x=np.zeros([2,3])
print(x)

print("\n ##################")
y=np.eye(3)
print(y)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 ##################
[[0. 0. 0.]
 [0. 0. 0.]]

 ##################
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
v1=np.arange(0,12)
v2=v1.reshape(4,3)
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

##### Arithmetic operations on arrays

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([1,2,3,4,5])
print("Sum of arrays=",a1+a2)

Sum of arrays= [ 2  4  6  8 10]


In [ ]:
m1=np.arange(1,5).reshape(2,2)
m2=np.eye(2)
print(m1)
print(m2)

print("\nDiv::",m1/m2)

[[1 2]
 [3 4]]
[[1. 0.]
 [0. 1.]]

Div:: [[ 1. inf]
 [inf  4.]]


C:\Users\dwivedik\AppData\Local\Temp\ipykernel_8100\965104536.py:6: RuntimeWarning: divide by zero encountered in divide
  print("\nDiv::",m1/m2)


In [ ]:
m1=np.arange(-9,0,1).reshape(3,3)
print(np.min(m1))
print(np.max(m1))

-9
-1


In [ ]:
import numpy as np

mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])

mat.mean()

np.cos([0, 1, 2, 3, 4])

mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1]=5
mat

array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

np.ones([2,2])

n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])

#Dot product
n1@n2

array_1 = np.linspace(0,20,6)
array_1

array_2 = np.arange(0,20,6)
array_2



21


array([ 0,  6, 12, 18])