<a href="https://colab.research.google.com/github/kdwivedi1985git/datascience/blob/main/numpy/numpy_savetoGDrive_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Saving numpy file to google drive

from google.colab import drive
drive.mount('/content/drive')

npmatrix=np.arange(0,12).reshape(3,4)

#save 1numpy array, #it saves the file as .npy file format
np.save('/content/drive/MyDrive/myfolder/myfile ',npmatrix)



#save multiple numpy arrays, saves file in .npz format (z=zip)
np.savez('/content/drive/MyDrive/myfolder/multiplefiles ',npmatrix=npmatrix, npmatrix2=npmatrix2)

# Load the numpy file

In [ ]:
onefile=np.load('/content/drive/MyDrive/myfolder/myfile.npy')
files=np.load('/content/drive/MyDrive/myfolder/multiplefiles.npz')

files['npmatrix']

# Save numpy arrays as .txt file

#save 1numpy array as txt format
np.savetxt('/content/drive/MyDrive/myfolder/myfile.txt ',npmatrix, delimiter=',')

#load txt file
np.loadtxt('/content/drive/MyDrive/myfolder/myfile.txt',delimiter=',')

#### Save and load numpy arrays in .npy and .npz file from local

In [ ]:
import numpy as np

npmatrix1= np.arange(0,12).reshape(3,4)
npmatrix2= np.arange(10,25).reshape(3,5)
npmatrix3= np.random.randint(2,13,15).reshape(5,3)

#save one file
np.save('sampledata/numpyfiles/mynpmatrix',npmatrix1)

#save multiple files as zip in one
np.savez('sampledata/numpyfiles/multiplematrixes',npmatrix1=npmatrix1,npmatrix2=npmatrix2,npmatrix3=npmatrix3)

print("numpy array saved in single file as well as zip")


numpy array saved in single file as well as zip


In [ ]:
print("retrive numpy files")

npfile=np.load('sampledata/numpyfiles/mynpmatrix.npy')
print(npfile)


npfiles=np.load('sampledata/numpyfiles/multiplematrixes.npz')
print("\n",npfiles)

npfiles['npmatrix2']

retrive numpy files
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 NpzFile 'sampledata/numpyfiles/multiplematrixes.npz' with keys: npmatrix1, npmatrix2, npmatrix3


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### save and load numpy arrays in txt files

In [ ]:
np.savetxt('sampledata/numpyfiles/mynpmatrix.txt',npmatrix1,delimiter=",")

file=np.loadtxt('sampledata/numpyfiles/mynpmatrix.txt',delimiter=",")

file

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])